@startuml PhysicalExtend

package under {
    package extend {
        package ex_stage {
            package ex_physics {
                package ex_collider {
                    class CircleCollider {
                        #radius : number
                        #shiftX : number
                        #shiftY : number
                        #centerX : number
                        #centerY : number
                    }
                    class RectangleCollider {
                        #startX : number
                        #startY : number
                        #endX : number
                        #endY : number
                    }
                    class RoundRectangleCollider {
                        #cut : number
                    }
                }
                package ex_body {
                    class MaxAdoptBody {
                        #vpx : number
                        #vpy : number
                        #vmx : number
                        #vmy : number
                        #preX : number
                        #preY : number
                    }
                    class PreciseBody
                    class PlayerBody
                    class JointBody {
                        JointBody(jointingX,jointingY,jointed,jointedX,jointedY,length) : JointingBody
                        #jointingX : number
                        #jointingY : number
                        #jointed : Entity
                        #jointedX : number
                        #jointedY : number
                        #length : number
                    }
                    class ImmutableRigidMaterial {
                        ImmutableRigidMaterial(k,frictionX,frictionY) : ImmutableRigidMaterial
                        #kVal : number
                        #frictionXVal : number
                        #frictionYVal : number
                    }
                }
                package ex_material {
                    class ImmutableMaterial  {
                        ImmutableMaterial(mass,elasticity,mu) : ImmutableMaterial
                        #massVal : number
                        #eVal : number
                        #muVal : number
                    }
                }
            }
        }
    }
}

package under {
    package base {
        package stage {
            package physics {
                package colloder {
                    abstract Collider
                }
                package body {
                    abstract RigidBody
                    abstract RigidMaterial
                }
                package material {
                    abstract Material
                }
            }
        }
    }
}

Collider <|.. RectangleCollider
Collider <|.. CircleCollider
RectangleCollider <|-- RoundRectangleCollider
RigidBody <|.. MaxAdoptBody
MaxAdoptBody <|-- PlayerBody
MaxAdoptBody <|-- PreciseBody
MaxAdoptBody <|-- JointBody
RigidMaterial <|.. ImmutableRigidMaterial
Material <|.. ImmutableMaterial

@enduml
