@startuml EntityExtendFire
package under {
    package extend {
        package ex_stage {
            package ex_entity {
                package ex_fire {
                    class ImmutableEvent {
                        #event : GameEvent
                        #collided : boolean
                        #eventCollider : Collider
                        +setEvent(event) <<override>>
                        +getEvent() : GameEvent <<override>>
                        +fire() <<override>>
                        +getCollider() : Collider <<override>>
                        +init() <<override>>
                        +update(dt) <<override>>
                    }
                    class OnceEventEntity {
                        +destroy() <<override>>
                        +fire() <<override>>
                    }
                }
            }
        }
    }
}

package under {
    package base {
        package event {
            abstract EventManager
            package common {
                abstract GameEvent
            }
        }
        package stage {
            abstract Stage
            package entity {
                abstract Entity
                package interface {
                    interface IPlayable
                    interface IEventEntity
                    interface IColliderable
                    interface IBreakable
                }
            }
            package physics {
                abstract PhysicalWorld
                package collider {
                    abstract Collider
                    abstract CollisionData
                }
            }
        }
    }
}

GameEvent <.. ImmutableEvent : Init and register
EventManager <.. ImmutableEvent : Register
Collider <.. ImmutableEvent : Set and get
Stage <.. ImmutableEvent : Get
PhysicalWorld <.. ImmutableEvent : Get
CollisionData <.. ImmutableEvent : Get
IPlayable <.. ImmutableEvent : Judge

Stage <.. OnceEventEntity : Remove

Entity <|.. ImmutableEvent
IEventEntity <|.. ImmutableEvent
IColliderable <|.. ImmutableEvent

ImmutableEvent <|-- OnceEventEntity
IBreakable <|.. OnceEventEntity

@enduml
