@startuml EntityExtend
package under {
    package extend {
        package ex_stage {
            package ex_entity {
                class TileObject {
                    #srcX : number
                    #srcY : number
                    #srcW : number
                    #srcH : number
                }
                class Obstacle
                class SingleAIObject {
                    #ai : Array<AI>
                }
                class Character {
                    #hp : number
                }
                class StateCharacter {
                    #state : State
                }
                class Enemy
                class Player {
                    -invincible_ : number
                }

                package ex_attack {
                    abstract AttackObject {
                        #lifespan : number
                        {abstract} #judgeCollision : bool
                    }
                    class PunchObject
                }
            }
        }
    }
}

package under {
    package base {
        package stage {
            package entity {
                abstract ImmutableObject
                abstract MutableObject
                abstract AutonomyObject
                abstract Damagable
                abstract Breakable
                abstract Playable
            }
        }
    }
}

ImmutableObject <|.. TileObject
MutableObject <|.. Obstacle
AutonomyObject <|.. SingleAIObject

SingleAIObject <|-- Character
Damagable <|.. Character
Character <|-- StateCharacter
StateCharacter <|-- Player
Playable <|.. Player
Character <|-- Enemy
SingleAIObject <|-- AttackObject
Breakable <|.. AttackObject
AttackObject <|.. PunchObject


@enduml
