@startuml EntityExtend
package under {
    package extend {
        package ex_stage {
            package ex_entity {
                class TileObject
                class Obstacle
                class AIListedObject {
                    #ai : Array<AI>
                    +addAI(ai,priotiy) <<override>>
                    +removeAI(ai) <<override>>
                    +updateAI(dt) <<override>>
                    +applyAI(dt) <<override>>
                }
                class Character {
                    #hp : number
                    +setHP(hp)
                    +getHP() : number <<override>>
                    +damage() : number <<override>>
                    +destroy() <<override>>
                }
                class StateCharacter {
                    #state : State
                    +applyAI(dt) <<override>>
                    +render(ctx,shiftX,shiftY) <<override>>
                }
                class Enemy
                class Player {
                    -invincible_ : number
                }

                package ex_attack {
                    abstract AttackObject {
                        #lifespan : number
                        {abstract} #judgeCollision : boolean
                    }
                    class PunchObject
                }
            }
        }
    }
}

package under {
    package base {
        package ai {
            abstract AI
        }
        package stage {
            abstract Stage
            package entity {
                abstract ImmutableObject
                abstract MutableObject
                abstract AutonomyObject
                package interface {
                    interface IDamagable
                    interface IBreakable
                    interface IPlayable
                }
            }
        }
    }
}

AI <.. AIListedObject : Update and apply
Stage <.. Character : Destroy

ImmutableObject <|.. TileObject
MutableObject <|.. Obstacle
AutonomyObject <|.. AIListedObject

AIListedObject <|-- Character
IDamagable <|.. Character
Character <|-- StateCharacter
StateCharacter <|-- Player
Playable <|.. Player
Character <|-- Enemy
AIListedObject <|-- AttackObject
Breakable <|.. AttackObject
AttackObject <|.. PunchObject


@enduml
