@startuml EntityGame
package game {
    package ga_stage {
        package ga_entity {
            class UnderPlayer {
                #aiType : AI
                +changeType(ground)
            }
            class UnderTileObject {
                +terrainID : number
            }
        }

        package ga_ai {
            package ga_player {
                class PUnderState {
                    -underCount_ : number
                }
                class UnderStateAI {

                }
                package ga_wild {
                    class WildBaseStateAI
                    class WildJumpState
                    class WildClawState
                }
            }
        }
    }
}

package under {
    package extend {
        package ex_stage {
            package ex_entity {
                class TileObject
                class Player
            }
            package ex_ai {
                class NamedStateAI
                abstract BaseState
                package ex_player {
                    class PStationaryState
                    class PWalkState
                    class PJumpState
                    class PJumpingState
                    class PPunchState
                }
            }
        }
    }
}

UnderStateAI ..> PUnderState : Generate
WildBaseStateAI ..> PStationaryState : Generate
WildBaseStateAI ..> PWalkState : Generate
WildBaseStateAI ..> WildJumpState : Generate
WildBaseStateAI ..> PJumpingState : Generate
WildBaseStateAI ..> WildClawState : Generate

PUnderState .> UnderPlayer : Use method

Player <|--- UnderPlayer
TileObject <|--- UnderTileObject

BaseState <|... PUnderState
NamedStateAI <|--- UnderStateAI
NamedStateAI <|--- WildBaseStateAI

PJumpState <|-- WildJumpState
PPunchState <|-- WildClawState

@enduml
