@startuml EntityGame
package game {
    package ga_stage {
        package ga_entity {
            class UnderTileObject {
                +terrainID : number
            }
            package ga_character {
                class UnderPlayer {
                    #aiType : TransferableStateAI
                    #preTerrain : number
                    +addAI(ai,priority) MMoverride>>
                    +changeType(id) : boolean <<override>>
                }
            }
            package ga_object {
                class TextSignObject {
                    #signText : string
                    #size : number
                    #isExec : boolean
                    +setSign(x, y, size, text)
                    +init() <<override>>
                    +update(dt) <<override>>
                    +render(ctx,shiftX,shiftY) <<override>>
                }
            }
            package ga_interface {
                interface ITerrain {
                    {abstract} +getTerrainID() : number
                }
                interface IUnderPlayable {
                    {abstract} +changeType(id) : boolean
                }
                interface IHook {
                    {abstract} +getActor() : Entity
                    {abstract} +createPost()
                    {abstract} +hooked()
                    {abstract} +release()
                    {abstract} +tryRemove() : boolean
                    {abstract} +isHead() : boolean
                }
            }
        }
    }
}

package under {
    package base {
        package resource {
            interface IImageManager
            package image {
                abstract MultiAnimation
            }
        }
        package physics {
            package body {
                abstract RigidBody
                abstract RigidMaterial
            }
        }
    }
    package extend {
        package ex_stage {
            package ex_entity {
                class TileObject
                class Player
                package ex_object {
                    class SignObject
                }
            }
        }
    }
}
package game {
    package ga_stage {
        package ga_ai {
            abstract TransferableStateAI
            package ga_player {
                package ga_normal {
                    class NormalBaseStateAI
                }
                package ga_wild {
                    class WildBaseStateAI
                }
                package ga_adventurer {
                    class AdventurerBaseStateAI
                }
                package ga_propeller {
                    class PropellerBaseStateAI
                }
            }
        }
    }
}

UnderPlayer ..> WildBaseStateAI : Generate
UnderPlayer ..> NormalBaseStateAI : Generate
UnderPlayer ..> AdventurerBaseStateAI : Generate
UnderPlayer ..> PropellerBaseStateAI : Generate
UnderPlayer ..> TransferableStateAI : Transfer
RigidBody <.. UnderPlayer : Set
RigidMaterial <.. UnderPlayer : Set
MultiAnimation <.. UnderPlayer : Set
IImageManager <.. UnderPlayer : Load

Player <|-- UnderPlayer
UnderPlayer ..|> IUnderPlayable
TileObject <|-- UnderTileObject
UnderTileObject ..|> ITerrain

SignObject <|-- TextSignObject

@enduml
