@startuml ParserBuilder

package under {
    package extend {
        package ex_stage {
            package ex_parser {
                class TileBuilder {
                    #makeCollider(collider) : Collider
                    #makeMaterial(material) : Material
                    #makeTileBase(tile, chip) : TileObject
                    #makeTileobject(tile,chip) : TileObject
                }

                class CharacterBuilder {
                    #makeBody(body) : RigidBody
                    #makeAnimation(anime) : NamedAnimation
                    #makeAI(ai, animation) : AI
                    #makeEntityBase(info, entity) : Entity
                }
            }
        }
    }
}

package under {
    package base {
        package context {
            class AnimationElement
        }
        package stage {
            package parser {
                abstract EntityBuilder
            }
        }
    }
    package extend {
        package ex_context {
            class SingleAnimation
            class MultiNamedAnimation
        }
        package ex_stage {
            package ex_physics {
                package ex_collider {
                    class CircleCollider
                    class RectangleCollider
                    class RoundRectangleCollider
                }
                package ex_material {
                    class ImmutableMaterial
                }
                package ex_body {
                    class ImmutableRigidMaterial
                    class MaxAdoptBody
                    class PreciseBody
                    class PlayerBody
                }
            }
            package ex_entity {
                class TileObject
                class Player
                class Enemy
                class Obstacle
            }
            package ex_ai {
                class BaseState
            }
        }

    }
}

TileBuilder ....> TileObject : Generate
TileBuilder ....> RectangleCollider : Generate
TileBuilder ....> CircleCollider : Generate
TileBuilder ....> RoundRectangleCollider : Generate
TileBuilder ....> ImmutableMaterial : Generate
TileBuilder ...> SingleAnimation : Generate
TileBuilder ...> MultiNamedAnimation : Generate
TileBuilder ...> AnimationElement : Generate
CharacterBuilder ...> MaxAdoptBody : Generate
CharacterBuilder ...> PreciseBody : Generate
CharacterBuilder ...> PlayerBody : Generate
CharacterBuilder ...> ImmutableRigidMaterial : Generate
CharacterBuilder ...> Player : Generate
CharacterBuilder ...> Enemy : Generate
CharacterBuilder ...> Obstacle : Generate
CharacterBuilder ...> BaseState : Set animation

EntityBuilder <|.. TileBuilder
TileBuilder <|-- CharacterBuilder

@enduml
