@startuml ParserCSV

package under {
    package extend {
        package ex_stage {
            class CSVStageParser {
                #makeBaseStage() : Stage
                #makeBaseBackground(imageID,width,height) : Background
                #makeBaseCamera(width,height) : Camera
                #makeBaseWorld() : PhysicalWorld
                #makeTileobject(verticalId,horizontalId,tileWidth,tileHeight,x,y,width,height,imageID) : TileObject
            }
        }
    }
}

package under {
    package base {
        package stage {
            abstract StageParser
        }
    }
    package extend {
        package ex_stage {
            class SplitManagementStage
            package ex_camera {
                class CenterCamera
            }
            package ex_back {
                class InvariantBackground
            }
            package ex_physics {
                class SequentialWorld
                class RepulsionResponse
                package ex_collider {
                    class RectangleCollider
                }
                package ex_material {
                    class ImmutableMaterial
                }
            }
            package ex_entity {
                class TileObject
            }
        }
    }
}

CSVStageParser ...> SplitManagementStage : Generate
CSVStageParser ...> CenterCamera : Generate
CSVStageParser ...> InvariantBackground : Generate
CSVStageParser ...> SequentialWorld : Generate
CSVStageParser ...> RepulsionResponse : Generate
CSVStageParser ...> TileObject : Generate
CSVStageParser ...> RectangleCollider : Generate
CSVStageParser ...> ImmutableMaterial : Generate

StageParser <|.. CSVStageParser

@enduml
