@startuml ParserImage

package under {
    package extend {
        package ex_stage {
            package ex_parser {
                class BaseImageBuilder {
                    +build(root,image) : GameImage <<override>>
                }
            }
        }
    }
}

package under {
    package base {
        package resource {
            interface IImageManager
        }
        package stage {
            package parser {
                abstract ImageBuilder
            }
        }
    }
    package extend {
        package ex_resource {
            package ex_image {
                class TileImage
                class SingleImage
                class SingleAnimation
                class MultiNamedAnimation
                package ex_directional {
                    class DirectionalImage
                    class DirectionalAnimation
                    class DirectionalNamedAnimation
                }
                package ex_clip {
                    class ClipImage
                    class ClipAnimation
                }
                package ex_transition {
                    class TransitionalNamedAnimation
                    class TransitionalStripeAnimation
                }
            }
        }
    }
}

BaseImageBuilder ..> TileImage : Generate
BaseImageBuilder ..> SingleImage : Generate
BaseImageBuilder ..> SingleAnimation : Generate
BaseImageBuilder ..> MultiNamedAnimation : Generate

BaseImageBuilder ..> TransitionalNamedAnimation : Generate
BaseImageBuilder ..> TransitionalStripeAnimation : Generate

BaseImageBuilder ..> ClipImage : Generate
BaseImageBuilder ..> ClipAnimation : Generate

BaseImageBuilder ..> DirectionalImage : Generate
BaseImageBuilder ..> DirectionalAnimation : Generate
BaseImageBuilder ..> DirectionalNamedAnimation : Generate

IImageManager <.. BaseImageBuilder : Load

ImageBuilder <|.. BaseImageBuilder

@enduml
