@startuml ParserJSON

package under {
    package extend {
        package ex_stage {
            package ex_parser {
                class JSONStageParser {
                    +JSONStageParser(tile,chara) : JSONStageParser
                    #tileBuilder : EntityBuilder
                    #charaBuilder : EntityBuilder
                    #makeBaseStage(stage) : Stage
                    #makeBaseMap(map) : Map
                    #makeMapElement(map,back) : Map
                    #makeBaseCamera(camera,width,height) : Camera
                    #makeBaseWorld() : PhysicalWorld
                    #addTile(base,chip,tileInfo)
                    #addEntity(base,entity,entityInfo)
                }
            }
        }
    }
}

package under {
    package base {
        package stage {
            package parser {
                abstract StageParser
            }
        }
    }
    package extend {
        package ex_stage {
            class SplitManagementStage
            class DebugStage
            package ex_parser {
                class TileBuilder
                class CharacterBuilder
            }
            package ex_camera {
                class MovingCenterCamera
            }
            package ex_map {
                class InvariantBackMap
                class SequentialMap
            }
            package ex_physics {
                class SequentialWorld
                class DebugWorld
                class RepulsionResponse
            }
        }

    }
}

JSONStageParser ..> SplitManagementStage : Generate
JSONStageParser ..> DebugStage : Generate
JSONStageParser ..> MovingCenterCamera : Generate
JSONStageParser ..> SequentialMap : Generate
JSONStageParser ..> InvariantBackMap : Generate
JSONStageParser ..> SequentialWorld : Generate
JSONStageParser ..> DebugWorld : Generate
JSONStageParser ..> RepulsionResponse : Generate

JSONStageParser ..> TileBuilder : "Default"
JSONStageParser ..> CharacterBuilder : "Default"

StageParser <|.. JSONStageParser

@enduml
