@startuml ParserJSON

package under {
    package extend {
        package ex_stage {
            package ex_parser {
                class JSONStageParser {
                    +constructor(tile,chara,event,image)
                    #tileBuilder : EntityBuilder
                    #charaBuilder : EntityBuilder
                    #eventBuilder : EventBuilder
                    #imageBuilder : imageBuilder
                    #makeBackgroundImage(image) : GameImage
                    #makeBaseStage(stage) : Stage
                    #makeBackground(back) : Background
                    #makeBaseCamera(camera) : Camera
                    #makeBaseWorld(stage,world) : PhysicalWorld
                    #makePhysicalResponse() : CollisionResponse
                    #makeTile(base,chip,tileInfo) : Entity
                    #makeEntity(base,entity,entityInfo) : Entity
                    #buildTileInfo(tileInfo,tiles)
                    #buildEntityInfo(entityInfo:entities)
                    +parse(filePath,width,height) : Stage <<override>>
                }
            }
        }
    }
}

package under {
    package base {
        package resource {
            package image {
                interface IImageManager
            }
        }
        package stage {
            abstract Stage
            package camera {
                abstract Camera
            }
            package entity {
                package interface {
                    interface IEventEntity
                }
            }
            package parser {
                abstract StageParser
            }
            package physics {
                abstract PhysicalWorld
            }
        }
    }
    package extend {
        package ex_event {
            class SimpleEventBuilder
        }
        package ex_stage {
            class SplitManagementStage
            package ex_parser {
                class TileBuilder
                class CharacterBuilder
                class BaseImageBuilder
            }
            package ex_camera {
                class CenterCamera
                class ClipCamera
                class MovingCamera
                class ForceMoveCamera
            }
            package ex_back {
                class SequentialBackground
                class InvariantBackground
                class MovementBackground
                class AreaBackground
                class FixedBackground
            }
            package ex_physics {
                class SequentialWorld
                class SplitWorld
                class GravityWorld
                class RepulsionResponse
            }
        }

    }
}

JSONStageParser .> SplitManagementStage : Generate
JSONStageParser ...> SequentialBackground : Generate
JSONStageParser ...> InvariantBackground : Generate
JSONStageParser ...> MovementBackground : Generate
JSONStageParser ...> AreaBackground : Generate
JSONStageParser ...> FixedBackground : Generate
JSONStageParser ....> CenterCamera : Generate
JSONStageParser ....> ClipCamera : Generate
JSONStageParser ....> MovingCamera : Generate
JSONStageParser ....> ForceMoveCamera : Generate
JSONStageParser .....> SequentialWorld : Generate
JSONStageParser .....> SplitWorld : Generate
JSONStageParser .....> GravityWorld : Generate and init
JSONStageParser .....> RepulsionResponse : Generate
IImageManager <..  JSONStageParser: Load
Stage <..  JSONStageParser: Initialize
PhysicalWorld <..  JSONStageParser: Initialize
IEventEntity <.. JSONStageParser : Set
Camera <.. JSONStageParser : Init

JSONStageParser ..> TileBuilder : Default
JSONStageParser ..> CharacterBuilder : Default
JSONStageParser ..> BaseImageBuilder : Default
JSONStageParser ..> SimpleEventBuilder : Default

StageParser <|.. JSONStageParser

@enduml
