@startuml StageExtend
package under {
    package extend {
        package ex_stage {
            class SplitManagementStage {
                #mutables : Array<MutableObject>
                #entities : Array<Entity>
                #player : Playable
            }
            class DebugStage
            package ex_back {
                class SequentialBackground {
                    #backs : Array<Background>
                }
                class InvariantBackground {
                    +constructor(imageID)
                    #backID : number
                }
            }
            package ex_camera {
                class CenterCamera
                class MovingCenterCamera
            }

            package ex_physics {
                class SequentialWorld {
                    #collisions : Array<CollisionData>
                    #collisionSize : number
                    #actors : Array<Entity>
                    #notActors : Array<Entity>
                    #entities : Array<Entity>
                }
                class ImpulseBasedResponse
                class RepulsionResponse
            }
        }
    }
}

package under {
    package base {
        package stage {
            abstract Stage
            package back {
                abstract Background
            }
            package camera {
                abstract Camera
            }
            package physics {
                abstract PhysicalWorld
                abstract CollisionResponse
                package collider {
                    class CollisionData
                }
            }
        }
    }
}

CollisionData <.. ImpulseBasedResponse : Collision response
CollisionData <.. RepulsionResponse : Collision response
CollisionData "1"--o "*"SequentialWorld : Pool

Stage <|.. SplitManagementStage
SplitManagementStage <|-- DebugStage
Camera <|.. CenterCamera
CenterCamera <|-- MovingCenterCamera
Background <|.. SequentialBackground
Background <|.. InvariantBackground
PhysicalWorld <|.. SequentialWorld
CollisionResponse <|.. ImpulseBasedResponse
CollisionResponse <|.. RepulsionResponse

@enduml
