@startuml GameBaseBase

package under {
    package base {
        abstract EngineBuilder {
            {abstract} #makeEngine() : Engine
            {abstract} #makeInput() : Input
            {abstract} #makeScreen() : Screen
            {abstract} #makeContext() : Context
            {abstract} #makeImageManager() : IImageManager
            {abstract} #makeMusic() : Music
            {abstract} #makeMusicManager() : IMusicManager
            {abstract} #makeTimer() : Timer
            {abstract} #makeSceneManager() : SceneManager
            +build() : Engine
        }
        abstract Engine {
            #input : Input
            #screen : Screen
            #manager : SceneManager
            #context : Context
            #music : Music
            #timer : Timer
            +setInput(input)
            +setScreen(screen)
            +setContext(context)
            +setSceneManager(manager)
            +setMusic(music)
            +setTimer(timer)
            +execute(scene)
            {static} +debug : bool
            {abstract} #main()
        }

        package input {
            abstract Input {
                {static} +it : IInput /' Singleton '/
                {static} +key : IKey /' Singleton '/
                {static} +mouse : IMouse /' Singleton '/
                #screen : Screen
                +setScreen(screen)
                {abstract} +init()
                {abstract} +update()
                {abstract} #clear()
            }

            interface IInput {
                {abstract} +blockInput(code)
                {abstract} +isPress(code) : bool
                {abstract} +isPressed(code) : bool
            }

            interface IKey {
                {abstract} +a() : number
                {abstract} +zero() : number
                {abstract} +right() : number
                {abstract} +left() : number
                {abstract} +up() : number
                {abstract} +down() : number
                {abstract} +yes() : number
                {abstract} +no() : number
                {abstract} +sub() : number
            }

            interface IMouse {
                {abstract} +mRight() : number
                {abstract} +mLeft() : number
                {abstract} +mCenter() : number
                {abstract} +getMouseX() : number
                {abstract} +getMouseY() : number
            }
        }

        package screen {
            abstract Screen {
                +Screen(width, height) : Screen
                {static} +it : Screen /' Singleton '/
                +gameSize : number
                +width : number
                +height : number
                {abstract} +init()
                {abstract} +getTarget() : Element
                {abstract} +getCanvas() : Canvas
            }
        }

        package resources {
            abstract ResourceManager {
                ResrouceManager(root) : ResrouceManager
                #root : string
                {static} +image : ResrouceManager
                {static} +music : ResrouceManager
                {abstract} +load(filePath) : Object
                {abstract} +unload(id)
                {abstract} +reload
                {abstract} +getPath(id) : string
            }
            interface IImageManager {
                {abstract} +getWidth(id) : number
                {abstract} +getHeight(id) : number
                {abstract} +getImage(id) : Image
            }
            interface IMusicManager {
                {abstract} +getMusic(id) : BufferSource
            }

            package music {
                abstract Music {
                    {static} +it : Music /' Singleton '/
                    #music : IMusicManager
                    +setMusicManager(musicManager)
                    {abstract} +playSE(musicID)
                    {abstract} +playBGM(musicID)
                    {abstract} +pauseBGM()
                    {abstract} +resumeBGM()
                    {abstract} +stopBGM()
                }
            }

            package image {
                abstract Context {
                    #screen : Screen
                    #image : IImageManager
                    +setScreen(screen)
                    {abstract} +setImageManager(imageManager)
                    {abstract} +setFontColorByame(colorName)
                    {abstract} +setFontColorByRGB(r,g,b)
                    {abstract} +setFontSize(size)
                    {abstract} +setFontName(fontName)
                    {abstract} +preRendering()
                    {abstract} +postRendering()
                    {abstract} +fillText(text,x,y,anchorX,anchorY,size,color,font)
                    {abstract} +strokeLine(sx,sy,ex,ey,color,lineWidth)
                    {abstract} +strokeCircle(x,y,radius,startAngle,endAngle,anticlockwise,color,lineWidth)
                    {abstract} +strokeRect(x,y,width,height,color,lineWidth)
                    {abstract} +fillRect(x,y,width,height,color,lineWidth)
                    {abstract} +drawImage(imageID,x,y,width,height,srcX,srcY,srcW,srcH)
                }

                abstract Animation {
                    {abstract} +init()
                    {abstract} +setLoop(loop)
                    {abstract} +isLoop() : bool
                    {abstract} +isEnded() : bool
                    {abstract} +getAnimationCount() : number
                    {abstract} +addAnimation(element)
                    {abstract} +pause()
                    {abstract} +restore()
                    {abstract} +update(dt)
                    {abstract} +render(ctx,x,y,width,height,imageID)
                }
                abstract MultiAnimation {
                    {abstract} +getAnimation() : Animation
                    {abstract} +setAnimation(animation)
                }
                abstract NamedAnimation {
                    {abstract} +setName(name) : NamedAnimation
                }
                class AnimationElement {
                    +imageID : number
                    +srcX : number
                    +srcY : number
                    +srcW : number
                    +srcH : number
                    +delta : number
                }
            }
        }

        package scene {
            abstract SceneManager {
                {static} +it : SceneManager /' Singleton '/
                {abstract} +getScene() : Scene
                {abstract} +pushScene(scene)
                {abstract} +popScene()
                {abstract} +replaceScene(scene)
                {abstract} +update(dt)
                {abstract} +render(ctx)
            }
            abstract Scene {
                {abstract} +init()
                {abstract} +update(dt)
                {abstract} +render(ctx)
            }

            package layer {
                abstract Layer {
                    {abstract} +update(dt)
                    {abstract} +render(ctx)
                }
            }
        }

        package timer {
            abstract Timer {
                {static} +it : Timer /' Singleton '/
                #deltaTime : number
                {abstract} +init()
                {abstract} +update(dt)
                {abstract} +startTimer(name)
                {abstract} +stopTimer(name)
                {abstract} +getTimer(name) : number
                {abstract} +getRegisteredNames() : Array<string>
            }
        }

        package util {
            class BaseUtil {
                {static} +implementsOf(instance,i) : bool
            }
            class Interface {
                -methods_ : Array<Method>
                #addMethod(method)
                +validate(instance) : bool
            }
            class Method {
                +Method(name,number) : Method
                +name : string
                +length : number
            }
        }
    }
}

EngineBuilder --> Engine : Generate
Engine "1"*-- "1" Screen : Own
Engine "1"*-- "1" Input : Own
Engine "1"*-- "1" SceneManager : Own
Engine "1"*-- "1" Context : Own
Engine "1"*-- "1" Music : Own

Input .> Screen : Input target
Context .> Screen : Rendering target

Input ..> IInput : Singleton
Input ..> IKey : Singleton
Input ..> IMouse : Singleton

Context ..> IImageManager : Get resource
Music ..> IMusicManager : Get resource
IImageManager <.. ResourceManager : Set singleton
IMusicManager <.. ResourceManager : Set singleton

SceneManager "1"*--"*" Scene : Should own
Scene "1" o--"*" Layer : May own

Animation "1"*--"*"AnimationElement : Should own

IInput <|-- IKey
IInput <|-- IMouse

Animation <|-- MultiAnimation
MultiAnimation <|-- NamedAnimation

Interface ..> Method : Use

@enduml
