@startuml GameBaseGame

package game {
    class Main
    class MainBuilder
}

package under {
    package extend {
        class UnderEngineBuilder
        package ex_input {
            class PreventKeyInput
        }
    }
}

package game {
    package ga_scene {
        class TitleScene
    }
}


Main ..> MainBuilder : Generate
Main ..> TitleScene : Generate
MainBuilder ..> PreventKeyInput : Generate

MainBuilder --|> UnderEngineBuilder

@enduml
