@startuml GameBaseGame

package game {
    class Main
    class MainBuilder
    package ga_input {
        class ExtendedInput {
            #subYes : number
            #subNo : number
        }
    }
}

package under {
    package extend {
        class UnderEngineBuilder
        package ex_input {
            class AllInput
        }
    }
}

package game {
    package ga_scene {
        class TitleScene
    }
}


Main ..> MainBuilder : Generate
Main ..> TitleScene : Generate
MainBuilder ..> ExtendedInput : Generate

MainBuilder --|> UnderEngineBuilder
ExtendedInput --|> AllInput

@enduml
