@startuml UnderEngine

package Under {
    class UnderEngine
    abstract Scene
    abstract Input

    package default_main {
        class DefaultScene
        class DefaultInput
    }

    package stage {
        abstract Stage
        abstract Map
        abstract Entity
        abstract StageParser

        package entity {
            abstract ImmutableObject
            abstract MutableObject
            abstract Character

            package physics {
                abstract RigidBody
            }
        }

        package default_stage {
            class DefaultStage
            class DefaultMap
            class DefaultStageParser
            class DefaultImmutableObject
            class DefaultPlayer
            class DefaultEnemy
        }
    }
}

package scene {
    class TitleScene
    class GameScene
}

Main --> UnderEngine

UnderEngine --> Input
UnderEngine --> Scene

Input <|.. DefaultInput
DefaultInput <|- ExtendInput

Scene <|.. DefaultScene
Scene o-- Stage

Scene <|.. TitleScene
Scene <|.. GameScene

Stage o-- Entity
Stage *-- Map
Stage *-- StageParser

Entity <|.. ImmutableObject
Entity <|.. MutableObject
MutableObject <|.. Character

Character <|.. DefaultPlayer
Character <|.. DefaultEnemy

ImmutableObject o-- RigidBody
MutableObject o-- RigidBody
Character o-- RigidBody

Stage <|.. DefaultStage
Map <|.. DefaultMap
StageParser <|.. DefaultStageParser
ImmutableObject <|.. DefaultImmutableObject

@enduml