@startuml UnderEngine

package under {
    package base {
        abstract Engine
        abstract Input
        abstract Screen

        package context {
            abstract ContextImage
            abstract Context
        }

        package scene {
            abstract SceneManager
            abstract Scene
        }

        package stage {
            abstract StageParser
            abstract Stage
            abstract Map
            abstract Entity
            abstract Camera
            abstract PhysicalWorld
            package entity {
                abstract ImmutableObject
                abstract MutableObject
                abstract AutonomyObject
                package physics {
                    abstract Collider
                    abstract RigidBody
                }
                package ai {
                    abstract AI
                }
            }
        }
    }

    package extend {
        class UnderEngine
        class AllInput
        class GeneratableScreen

        package ex_context {
            class JSContext
            class JSCachedImage
        }

        package ex_scene {
            class StackSceneManager
            class DefaultTitleScene
        }

        package ex_stage {
            class ConcreteStageParser
            class SplitManagementStage
            class InvariantBackMap
            class CenterCamera
            package ex_entity {
                class TileObject
                class Obstacle
                package ex_physics {
                    class CircleCollider
                    class GravityElasticBody
                }
            }
        }
    }
}

package main_scene {
    class TitleScene
    class GameScene
}

class ExtendedInput
class Main

Engine "1" *-- "1" Screen
Engine "1" *-- "1" Input
Engine "1" *-- "1" Context
Engine "1" *-- "1" SceneManager

SceneManager -> Input
Input -> Screen
Context -> Screen

SceneManager "1" *-- "*" Scene
SceneManager <-- Scene
Input <-- Scene
Context "1" *-- "1" ContextImage

StageParser --> Stage
Stage "1" *-- "1" Map
Stage "1" *-- "1" Camera
Stage "1" *-- "*" Entity
Stage "1" *-- "1" PhysicalWorld

Entity <|-- ImmutableObject
Entity <|-- MutableObject
MutableObject <|-- AutonomyObject

Entity "1" o-- "1" Collider
MutableObject "1" *-- "1" RigidBody
AutonomyObject "1" *-- "*" AI

@enduml
