@startuml UnderEngine

package Under {
    class UnderEngine
    abstract Scene
    abstract Input

    package default_main {
        class DefaultTitleScene
        class AllInput
    }

    package stage {
        abstract Stage
        abstract Map
        abstract Entity
        abstract StageParser

        package entity {
            abstract ImmutableObject
            abstract MutableObject
            abstract Character

            package physics {
                abstract RigidBody
            }
        }

        package default_stage {
            class SplitManagementStage
            class InvariantBackMap
            class ConcreteStageParser
            class TileObject
            class DefaultPlayer
            class DefaultEnemy
        }
    }
}

package scene {
    class TitleScene
    class GameScene
}

Main --> UnderEngine

UnderEngine --> Input
UnderEngine --> Scene

Input <|.. AllInput
AllInput <|- ExtendInput

Scene <|.. DefaultTitleScene
Scene o-- Stage

Scene <|.. TitleScene
Scene <|.. GameScene

Stage o-- Entity
Stage *-- Map
Stage *-- StageParser

Entity <|.. ImmutableObject
Entity <|.. MutableObject
MutableObject <|.. Character

Character <|.. DefaultPlayer
Character <|.. DefaultEnemy

ImmutableObject o-- RigidBody
MutableObject o-- RigidBody
Character o-- RigidBody

Stage <|.. SplitManagementStage
Map <|.. InvariantBackMap
StageParser <|.. ConcreteStageParser
ImmutableObject <|.. TileObject

@enduml