@startuml EditorGameBase

package editor {
    class EditorMain
    class EditorBuilder

    package ed_context {
        class EditorContext
    }
}

package under {
    package extend {
        abstract UnderEngineBuilder
        package ex_context {
            class JSContext
            class CachedImage
        }
        package ex_screen {
            class FitableScreen
        }
    }
}

package editor {
    package ed_scene {
        class EditorScene
    }
}

EditorBuilder <.. EditorMain : "Execute"
EditorScene <.. EditorMain : "Generate"
FitableScreen <.. EditorBuilder : "Generate"
EditorContext <.. EditorBuilder : "Generate"
CachedImage <.. EditorBuilder : "Generate"

UnderEngineBuilder <|... EditorBuilder
JSContext <|-- EditorContext

@enduml
