@startuml EditorGameBase

package editor {
    class EditorMain
    class EditorBuilder

    package ed_context {
        class EditorContext
    }
    package ed_scene {
        class EditorScene {
            #stage : EditorStage
            #chipLayer : ChipLayer
        }
        package ed_layer {
            abstract SelectionLayer {
                +SelectionLayer(imageID) : SlectionLayer
                #imaeID : number
                #x : number
                #y : number
                #width : number
                #height : number
                #setPosition(x,y,width,height)
                #getSelectedTile() : number
                #setSelectedTile(id)
            }
            class ChipLayer {
                #tileInfo : Dictionary<number, json>
                #selectTile : json
                #selectedTile : json
            }
            class EntityLayer {
                #entityLayers : Array<SingleEntityLayer>
            }
            class SingleEntityLayer {
                #entity : json
                #animation : animation
                #selectEntity : json
                #selectedEntity : json
            }
        }
    }

    package ed_screen {
        class EditorScreen
    }
}

package under {
    package base {
        package context {
            class AnimationElement
        }
        package scene {
            package layer {
                abstract Layer
            }
        }
    }
    package extend {
        abstract UnderEngineBuilder
        package ex_context {
            class SingleAnimation
            class JSContext
            class CachedImage
        }
        package ex_scene {
            class LayerBaseScene
        }
        package ex_screen {
            class GeneratableScreen
        }
    }
}

package editor {
    package ed_stage {
        class EditorStage
        package ed_parser {
            class EditorStageParser
        }
    }
}

EditorBuilder <.. EditorMain : "Execute"
EditorScene <.. EditorMain : "Generate"
EditorScreen <.. EditorBuilder : "Generate"
EditorContext <.. EditorBuilder : "Generate"
CachedImage <.. EditorBuilder : "Generate"

EditorStageParser <.. EditorScene : "Parse"
ChipLayer <.. EditorScene : "Select chip"
EntityLayer <.. EditorScene : "Select entity"
EditorStage <.. EditorScene : "Set chip"

EntityLayer "1" o-- "*" SingleEntityLayer : "Manage"

SingleAnimation <... SingleEntityLayer : "Generate"
AnimationElement <... SingleEntityLayer : "Generate"

UnderEngineBuilder <|.. EditorBuilder
GeneratableScreen <|-- EditorScreen
JSContext <|-- EditorContext

LayerBaseScene <|-- EditorScene
Layer <|-- SelectionLayer
SelectionLayer <|.. ChipLayer
SelectionLayer <|.. EntityLayer
SelectionLayer <|.. SingleEntityLayer

@enduml
