@startuml SceneExtend

package under {
    package extend {
        package ex_scene {
            class StackSceneManager {
                #scenes : Array<Scene>
                #getScene() : Scene <<override>>
                +pushScene(scene) <<override>>
                +popScene() <<override>>
            }
            class BaseLayeredScene {
                #layers : Array<Layer>
                #sortedLayers : Array<Layer>
                +addLayer(layer) <<override>>
                +removeLayer(layer) <<override>>
                #getLayers() : Array<Layer> <<override>>
                +render(ctx) <<override>>
            }
            class DefaultTitleScene {
                -r_ : number
                -angle_ : number
                +update(dt) <<override>>
                +render(ctx) <<override>>
            }

            package ex_layer {
                class GameoverLayer {
                    +update(dt) <<override>>
                    +render(ctx) <<override>>
                }
                class FloatLayer {
                    +constructor(delegate)
                    #delegate : Layer
                    +setPosition(x,y,z) <<override>>
                    +setSize(width,heightC) <<override>>
                    +init() <<override>>
                    +update(dt) <<override>>
                    +render(ctx) <<override>>
                }
                class ScrollLayer {
                    +constructor(delegate)
                    #delegate : Layer
                    #scrollX : number
                    #scrollY : number
                    +scroll(x,y)
                    +init() <<override>>
                    +update(dt) <<override>>
                    +render(ctx) <<override>>
                }
                class DragScrollLayer {
                    +constructor(delegate)
                    #oldMouseX : number
                    #oldMouseY : number
                    #scrolling : boolean
                    +update(dt) <<override>>
                }
                abstract TabbedLayer {
                    +setPosition(x,y,z) <<override>>
                    +setSize(width,heightC) <<override>>
                    +update(dt) <<override>>
                    +render(ctx) <<override>>
                    +addTab(layer)
                    {abstract} +removeTab(layer)
                    {abstract} +getTab() : Layer
                    {abstract} +getTabs() : Array<Layer>
                }
                class NamedTabbedLayer {
                    #tabNames : Array<string>
                    #tabLayers : Array<Layer>
                    #currentlyTabIndex : number
                    #tabX : number
                    #tabY : number
                    #tabWidth : number
                    #tabHeight : number
                    #tabPadding : number
                    +addTabWithName(layer,name)
                    +addTab(layer) <<override>>
                    +removeTab(layer) <<override>>
                    +getTab() : Layer <<override>>
                    +getTabs() : Array<Layer> <<override>>
                    +update(dt) <<override>>
                    +render(ctx) <<override>>
                }
            }
        }
    }
}

package under {
    package base {
        package input {
            abstract IKey
            abstract IMouse
        }
        package resource {
            package image {
                abstract Context
            }
        }
        package scene {
            abstract Scene
            abstract LayeredScene
            abstract SceneManager
            package layer {
                abstract Layer
                abstract ClipLayer
            }
        }
    }
}

Context <.. DefaultTitleScene : Render
IKey <.. DefaultTitleScene : Get key
IMouse <.. DefaultTitleScene : Get mouse
Context <.. GameoverLayer : Render text

ClipLayer <.. ScrollLayer : Cliping

SceneManager <|.. StackSceneManager
LayeredScene <|.. BaseLayeredScene
Scene <|.. DefaultTitleScene

Layer <|.. GameoverLayer
Layer <|.. FloatLayer
Layer <|.. ScrollLayer
Layer <|.. TabbedLayer
ScrollLayer <|-- DragScrollLayer
TabbedLayer <|.. NamedTabbedLayer

@enduml
