@startuml SceneGame

package game {
    package ga_layer {
        class UILayer {
            #player : Player
            #playerHP : number
            #animationCount : number
            #animationFrame : number
            #animationState : number
            #uiImage : number
        }
    }
    package ga_scene {
        class GameScene {
            #stage : Stage
            #player : Player
            #gameover : bool
        }
    }
}

package under {
    package base {
        package scene {
            package layer {
                abstract Layer
            }
        }
    }

    package extend {
        package ex_context {
            class MultiNamedAnimation
        }
        package ex_scene {
            class LayerBaseScene
            package ex_layer {
                class GameoverLayer
            }
        }
        package ex_stage {
            package ex_entity {
                class Player
            }
        }
    }
}

package game {
    package ga_scene {
        class TitleScene
    }
    package ga_stage {
        class UnderStageParser
    }
}

GameScene ..> UnderStageParser : Generate
GameScene ..> UILayer : Generate
GameScene ..> GameoverLayer : Generate
GameScene ..> Player : Pass to another class, transtate gameover state
GameScene ..> TitleScene : Generate

UILayer ..> MultiNamedAnimation : Use

GameScene --|> LayerBaseScene
UILayer ..|> Layer

@enduml
