@startuml SceneGame

package game {
    package ga_layer {
        class DebugLayer {
            #deltaTime : number
            #collisions : number
            #playerCollisions : number
            #stage : Stage
            #player : Player
            #count : number
            #recode : Array<Object>
        }
        class UILayer {
            #player : Player
            #playerHP : number
            #animationCount : number
            #animationFrame : number
            #animationState : number
            #uiImage : number
        }
    }
    package ga_scene {
        class GameScene {
            #stage : Stage
            #player : Player
            #gameover : bool
        }
    }
}

package under {
    package base {
        package scene {
            package layer {
                abstract Layer
            }
        }
    }

    package extend {
        package ex_context {
            class MultiNamedAnimation
        }
        package ex_scene {
            class LayerBaseScene
            package ex_layer {
                class GameoverLayer
            }
        }
        package ex_stage {
            class SplitManagementStage
            package ex_entity {
                class Player
                package ex_physics {
                    class SequentialWorld
                    class ImpulseBasedResponse
                }
            }
        }
    }
}

package game {
    package ga_scene {
        class TitleScene
    }
    package ga_stage {
        class UnderStageParser
    }
}

GameScene ..> UnderStageParser : Generate
GameScene ..> DebugLayer : Generate
GameScene ..> UILayer : Generate
GameScene ..> GameoverLayer : Generate
GameScene ..> Player : Pass to another class, transtate gameover state
GameScene ..> TitleScene : Generate

DebugLayer ..> Player : Get player information
DebugLayer ..> ImpulseBasedResponse : Get physical state
DebugLayer ..> SplitManagementStage : Get stage information
DebugLayer ..> SequentialWorld : Get physical information

UILayer ..> MultiNamedAnimation : Use

GameScene --|> LayerBaseScene
DebugLayer ..|> Layer
UILayer ..|> Layer

@enduml
