@startuml SceneTitle

package game {
    package ga_scene {
        class TitleScene {
            -_title : GameImage
            +init() <<override>>
            +update(dt) <<override>>
            +render(ctx) <<override>>
        }
    }
}

package under {
    package base {
        package input {
            abstract IKey
        }
        package resource {
            interface IIMageManager
            package image {
                abstract GameImage
            }
        }
        package scene {
            abstract SceneManager
            abstract Scene
        }
    }

    package extend {
        package ex_resource {
            package ex_image {
                class SingleImage
                class GameText
            }
        }
    }
}

package game {
    package ga_scene {
        class GameScene
    }
}

SingleImage <..TitleScene : Generate
GameText <.. TitleScene : Generate
IIMageManager <.. TitleScene : Load
IKey <.. TitleScene : Get key
SceneManager <.. TitleScene : Replcae
GameImage <.. TitleScene : Render
TitleScene ..> GameScene : Generate

Scene <|.. TitleScene

@enduml
