@startuml AIWild
package game {
    package ga_stage {
        package ga_ai {
            package ga_player {
                package ga_wild {
                    class WildBaseStateAI
                    class WildClawState {
                        #makeAttackObject() : Entity <<override>>
                    }
                    class WildRollingState {
                        +apply(dt) <<override>>
                    }
                    class WildRollState {
                        +constructor(movePowerX,movePoserY)
                        +init() <<override>>
                        +apply(dt) <<override>>
                    }
                }
            }
        }
    }
}

package under {
    package base {
        package stage {
            abstract Stage
            package ai {
                abstract StateAI
            }
            package entity {
                abstract AutonomyEntity
            }
            package physics {
                package body {
                    abstract RigidBody
                }
            }
        }
    }
}

package game {
    package ga_stage {
        package ga_ai {
            interface IMovableState
            interface IPrepareState
            package ga_player {
                abstract UnderPlayerState
                abstract UnderMovableState
                package ga_normal {
                    class NormalBaseStateAI
                    class NormalPunchState
                }
            }
        }
    }
}

IMovableState <.. WildBaseStateAI : Transfer
IPrepareState <.. WildBaseStateAI : Transfer

WildBaseStateAI ..> WildClawState : Generate
WildBaseStateAI ..> WildRollState : Generate
WildBaseStateAI ..> WildRollingState : Generate

AutonomyEntity <.... WildClawState : Get
Stage <.... WildClawState : Create
StateAI <.... WildRollState : Change
AutonomyEntity <.... WildRollState : Get
RigidBody <.... WildRollState : Set and enforce

AutonomyEntity <.... WildRollingState : Get
RigidBody <.... WildRollingState : Set

NormalBaseStateAI <|-- WildBaseStateAI

WildClawState --|> NormalPunchState
WildRollingState ..|> UnderPlayerState
WildRollState ..|> UnderMovableState

@enduml
